Simulation Study
===

```{r}
library(recurrentR)
library(RPPGen)
library(plotrix)
```

# [@Wang2001]

## Parameters and Generators

```{r}
a <- 0.5
b <- 0.3
p <- 0.5
T_0 <- 10
n <- 400
lambda_0 <- local({
  lambda_0 <- function(u) 1/2 #default
  Total <- T_0 / 2
  function(u) { 
    lambda_0(u) / Total
  }
})
Lambda_0 <- function(u) u / T_0
h_0 <- function(u) k_y * u ^ (k_y - 1) / lambda_y ^ k_y
H_0 <- function(t) (t / lambda_y) ^ k_y

Ez <- 1
beta.true <- b
gamma.true <- c(log(Ez), a)

gen_huang_2010 <- function() {
	z <- rgamma(n,1/4,scale=4)	
	w <- rbinom(n,1,p)	
	x <- runif(n)
  x_t <- function(i) {
    force(i)
		u <- x[i] 
		function(t){u*log(t)}
	}
  X <- lapply(1:n, x_t)
  y <- mapply(function(w,z,x) ifelse(w==1, rexp(1,1/10),
  					ifelse(x>0.5, rexp(1,1/(6*z+4)),
							rexp(1,1/(10*x+5)))), w=w, z=z, x=x)
  y[y > T_0] <- T_0
  t <- vector("list", n)
  for(i in seq_len(n)) {
    lambda_i <- function(t) z[i]*exp(a*x[i] + b*X[[i]](t))*lambda_0(t)
    t[[i]] <- gen_inhomo_poisson(lambda_i, y[i], z[i] * exp(a * x[i] + b * x[i] * log(T_0) * b) * 1/2)
  }
  create_recurrent_data.list(X, y, y < T_0, t, T_0, matrix(x, nrow = n))
}
```

## Asymptotic Variance

```{r}
B <- 100
beta.hat <- numeric(B)
gamma.hat <- matrix(NA, B, 2)

for(i in 1:B) {
  obj <- gen_huang_2010()
  temp <- Huang2010(obj)
  beta.hat[i] <- temp$beta.hat
  gamma.hat[i,] <- temp$gamma.hat
}

# wang_2001 <- Wang2001(obj)
# huang_2004 <- Huang2004(obj=obj)
# curve(Lambda_0, 0, 10, col = 2, ylim = c(0, 1.2))
# Lambda_0.hat <- function(x) wang_2001$Lambda_0.hat(x)
# curve(Lambda_0.hat, add=TRUE, 0, 10, col = 1)
# Lambda_0.hat.upper <- Vectorize(function(x) wang_2001$Lambda_0.hat(x) + 2 * sqrt(wang_2001$Lambda_0.hat.var(x)))
# curve(Lambda_0.hat.upper, add=TRUE, col=1, 0, 10, lty = 2)
# Lambda_0.hat.lower <- Vectorize(function(x) wang_2001$Lambda_0.hat(x) - 2 * sqrt(wang_2001$Lambda_0.hat.var(x)))
# curve(Lambda_0.hat.lower, add=TRUE, col=1, 0, 10, lty = 2)
# 
# curve(H_0, 0, T_0, col = 2, ylim = c(0, H_0(T_0) * 1.1))
# lines(huang_2004$y, huang_2004$H0.hat.y)
# lines(huang_2004$y, huang_2004$H0.hat.y + qnorm(0.975) * huang_2004$H0.hat.y.sd, lty = 2)
# lines(huang_2004$y, huang_2004$H0.hat.y - qnorm(0.975) * huang_2004$H0.hat.y.sd, lty = 2)
# 
# plotCI(1:3, c(wang_2001$gamma.bar.hat, huang_2004$alpha.hat), uiw=qnorm(0.975) * c(sqrt(diag(wang_2001$gamma.bar.hat.var)), sqrt(diag(huang_2004$alpha.hat.var))))
# points(1:3, c(gamma.true, alpha.true), col = 2)
```

## Parametric Bootstrap

```{r}
B <- 20
gamma.hat <- matrix(NA, B, 2)
x.eval <- seq(from=0, to=T_0, length.out=100)
Lambda_0.hat <- matrix(NA, B, length(x.eval))
if (interactive()) pb <- txtProgressBar(max = B, style = 3)
for(i in seq_len(B)) {
  temp <- Wang2001(obj=gen_huang_2004())
  gamma.hat[i,] <- temp$gamma.bar.hat
  Lambda_0.hat[i,] <- temp$Lambda_0.hat(x.eval)
  gc()
  if (interactive()) setTxtProgressBar(pb, i)
}
if (interactive()) close(pb)
curve(Lambda_0, 0, 10, col = 2, ylim = c(0, 1.2))
y.eval <- apply(Lambda_0.hat, 2, mean)
y.eval.sd <- apply(Lambda_0.hat, 2, sd)
lines(x.eval, y.eval)
lines(x.eval, y.eval + qnorm(0.975) * y.eval.sd, lty = 2)
lines(x.eval, y.eval - qnorm(0.975) * y.eval.sd, lty = 2)
plotCI(1:2, apply(gamma.hat, 2, mean), uiw=apply(gamma.hat, 2, sd), 
       main = "Parametric Bootstrap", xlab = "", ylab = "", xaxt="n")
points(1:2, gamma.true, col = 2)
```