\section[Introduction]{Introduction}
\label{sec:introduction}
\addcontentsline{toc}{section}{\thesection. Introduction}

The package \pkg{recurrentR} was developed under the supervision of Dr. Chiung-Yu Huang. The purpose is to provide an easy-to-use implementation of the statistical methods proposed in \cite{Wang2001}, \cite{Huang2004}, and \cite{Huang2010} for recurrent event data analysis, where the observation of recurrent events can be terminated by a dependent failure event, such as death. To analyze recurrent events data with a correlated terminating event, many authors have proposed estimation procedures based on joint models of the recurrent event process and the terminal event, where the dependency between the two outcomes is modeled by a shared frailty. On the other hand, \cite{Wang2001}, \cite{Huang2004}, and \cite{Huang2010} have developed nonparametric and semiparametric estimation procedures that do not require complete specifications of the dependence structure.
