```{r pre}
library(recurrentR)
set.seed(1)
```

# Data Generation

```{r data-generation}
lambda <- function(x) exp(sin(x))
T_0 <- rpois(1, 40)

curve(lambda, from=0, to = T_0)

y <- rpois(nrow(iris), T_0)
y <- as.numeric(ifelse(y < T_0, y, T_0))
t <- sapply(y, function(y) {
	lambda_i <- function(t) exp(rnorm(1)) * lambda(t)
	as.numeric(ceiling(gen_inhomo_poisson(lambda_i, y - 1, 4)))
})
obj <- new("recurrent-data", model.matrix(~.,iris), y, t, data.frame(), T_0)
rm(list=c("y", "t", "T_0"), envir=globalenv())
```


# Estimate WQC2001 Model 1(No covariates)

```{r estimate-WQC2001-model-1}
F.hat <- obj$F.hat
Lambda.hat <- obj$Lambda.hat
curve(F.hat, 0, obj@T_0)
curve(Lambda.hat, 0, obj@T_0)

curve(lambda, 0, obj@T_0)
Lambda.single <- function(t) integrate(lambda, 0, t)$value
Lambda.single.T0 <- Lambda.single(obj@T_0)
Lambda <- function(t) {
	sapply(t, function(t) {
		Lambda.single(t) / Lambda.single.T0
	})
}
curve(Lambda, 0, obj@T_0, col=2)
curve(F.hat, 0, obj@T_0, add=TRUE, lty=1)
```

# Bootstrap Estimate

```{r estimate-WQC2001-model-1-bootstrap}
x.eval <- seq(from=0, to=obj@T_0, length=100)
# obj$F.hat(x.eval, TRUE, error.measurement.function=sd)
# obj$F.hat(x.eval, TRUE, error.measurement.function=function(a) c(quantile(a, 0.975), quantile(a, 0.025)))

result <- obj$F.hat(x.eval, TRUE, error.measurement.function=sd)
curve(Lambda, 0,obj@T_0, col=2)
lines(x.eval, result$estimate, col=1)
lines(x.eval, result$estimate + 2 * result$error.measurement, lty = 2, col = 1)
lines(x.eval, result$estimate - 2 * result$error.measurement, lty = 2, col = 1)

result <- obj$F.hat(x.eval, TRUE, error.measurement.function=function(a) c(quantile(a, 0.975), quantile(a, 0.025)))
curve(Lambda, 0,obj@T_0, col=2)
lines(x.eval, result$estimate, col=1)
lines(x.eval, result$error.measurement[1,], lty = 2, col = 1)
lines(x.eval, result$error.measurement[2,], lty = 2, col = 1)
```

# Generate Data with Covariate

```{r data-generation-covariate}
lambda <- function(x) exp(sin(x))
X <- model.matrix(~., data=iris)
beta <- rnorm(ncol(X)); beta[0] <- 0
beta[0] <- - max(X %*% beta)
T_0 <- rpois(1, 40)
y <- rpois(nrow(iris), T_0)
y <- as.numeric(ifelse(y < T_0, y, T_0))
t <- list()
pb <- txtProgressBar(max = length(y))
for(i in seq_along(y)) {
	lambda_i <- function(x) lambda(x) * exp(X[i,] %*% beta)
	t[[i]] <- gen_inhomo_poisson(lambda_i, T_0=T_0, exp(1) * exp(X[i,] %*% beta))
	setTxtProgressBar(pb, i)
}
close(pb)
obj <- new("recurrent-data", X, y, t, data.frame(), T_0)
rm(list=c("y", "t", "T_0"), envir=globalenv())
```

# Estimate WQC2001 Model 2

```{r estimate-WQC2001-model-1-bootstrap}
U.hat <- obj$U.hat

```