# recurrentR Demo: WQC2001

```{r loading-library}
library(recurrentR)
library(RPPGen)
```

# Experiment 1

## Setting Parameters and Covariates

```{r param1}
lambda <- function(x) exp(-x/10)
par(mfrow=c(1, 2))
curve(lambda, 0, 40)
Lambda <- function(x) 10 * (1 - exp(-x/10))
curve(Lambda, 0, 40)
T_0 <- rpois(1, 40)
gen_z <- function() runif(1, 0.5, 1.5)
n <- 150
beta <- c(1, -1)
X <- cbind(sin(1:n), sample(c(0, 1), n, TRUE))
```

## Generating Data

```{r gen1}
dev.off()
y <- rpois(n, T_0)
y <- as.numeric(ifelse(y < T_0, y, T_0))
t <- sapply(seq_along(y), function(i) {
	# 	browser()
	z <- gen_z() * exp(as.vector(X[i,] %*% beta))
	lambda_i <- function(t) z * lambda(t)
	retval <- gen_inhomo_poisson(lambda_i, y[i] - 1, lambda_i(0))
	if (is.null(retval)) return(vector("numeric", 0))
	return(retval)
	# 	return(as.numeric(ceiling(retval)))
})
obj <- new("recurrent-data", X, y, t, data.frame(), T_0)
```

## $\hat{\Lambda}$

```{r Lambda.hat1}
c.hat.gen <- recurrentR:::c.hat.gen(obj)
ci <- sapply(1:length(t), c.hat.gen)
# 	obj$Lambda.hat(T_0)

x.eval <- seq(0, obj@T_0, length=100)
y.eval <- obj$Lambda.hat(x.eval)
gamma <- obj$U.hat()
system.time({
	v <- asymptotic.var(obj, gamma = gamma)
	v.eval <- sapply(x.eval, function(x) v$Lambda.hat.var(x))
})
u.eval <- y.eval + 2*sqrt(v.eval)
l.eval <- y.eval - 2*sqrt(v.eval)
plot(x.eval, Lambda(x.eval), type="l", xlab="x", ylab="", 
	col = 3, lwd = 2, ylim=c(min(l.eval), max(u.eval)))
lines(x.eval, y.eval, lty=1, col = 1)
lines(x.eval, l.eval, lty=2)
lines(x.eval, u.eval, lty=2)
Lambda.hat <- obj$Lambda.hat
system.time({
	b.eval <- Lambda.hat(x.eval, bootstrap=TRUE)
})
u.eval <- y.eval + 2 * b.eval$error.measurement
l.eval <- y.eval - 2 * b.eval$error.measurement
lines(x.eval, u.eval, col=2, lty=2)
lines(x.eval, l.eval, col=2, lty=2)

m <- 100
real.sim <- matrix(0, length(x.eval), m)
U.sim <- matrix(0, length(beta) + 1, m)
# pb <- txtProgressBar(style=3, max=m)
for(i in 1:m) {
	y.sim <- rpois(n, T_0)
	y.sim <- as.numeric(ifelse(y.sim < T_0, y.sim, T_0))
	t.sim <- sapply(seq_along(y.sim), function(i) {
		# 	browser()
		z <- gen_z() * exp(as.vector(X[i,] %*% beta))
		lambda_i <- function(t) z * lambda(t)
		retval <- gen_inhomo_poisson(lambda_i, y.sim[i] - 1, lambda_i(0))
		if (is.null(retval)) return(vector("numeric", 0))
		return(retval)
		# 	return(as.numeric(ceiling(retval)))
	})
	obj.sim <- new("recurrent-data", X, y.sim, t.sim, data.frame(), T_0)
	real.sim[,i] <- obj.sim$Lambda.hat(x.eval)
	U.sim[,i] <- obj.sim$U.hat()
# 	setTxtProgressBar(pb, i)
}
# close(pb)

lines(x.eval, apply(real.sim, 1, function(a) quantile(a, 0.025)), lty=2, col=3, lwd=2)
lines(x.eval, apply(real.sim, 1, function(a) quantile(a, 0.975)), lty=2, col=3, lwd=2)

legend("bottomright", 
	c("Lambda.hat", "Lambda", "asymptotic pointwise C.I.", "bootstrap pointwise C.I.", "parametric bootstrap pointwise C.I."), 
	lty=c(1, 1, 2, 2, 2), col=c(1, 3, 1, 2, 3), lwd=c(1, 2, 1, 1, 2))
```

## $\hat{\gamma}$

- black: asymptotic C.I.
- red: bootstrap C.I.
- green: parametric bootstrap C.I. (quantile)

```{r gamma.hat1}
library(plotrix)
par(mfrow=c(1, length(gamma)))
asymptotic.gamma.sd <- sqrt(diag(v$gamma.var.hat))
invisible(capture.output(u.hat <- obj$U.hat(TRUE)))
param.bootstrap.U <- apply(U.sim, 1, function(a) quantile(a, c(0.025, 0.975)))
for(i in seq_along(gamma)) {
	plotCI(1:3, rep(gamma[i], 3), ui = c(gamma[i] + 2 * asymptotic.gamma.sd[i], gamma[i] + 2 * u.hat$error.measurement[i], param.bootstrap.U[2,i]), li=c(gamma[i] - 2 * asymptotic.gamma.sd[i], gamma[i] - 2 * u.hat$error.measurement[i], param.bootstrap.U[1,i]), 
		xaxt='n', xlab="", ylab = "", main=paste("gamma[", i, "]", sep=""), col=c(1,2,3), bty="n", xlim=c(0,3))
	if (i == 1) abline(h=log(Lambda(T_0)), col=3, lwd=2) else abline(h=beta[i-1], col=3, lwd=2)
}
```

# Experiment 2

## Setting Parameters and Covariates

```{r param2}
lambda <- function(x) rep(1, length(x))
par(mfrow=c(1, 2))
curve(lambda, 0, 40)
Lambda <- function(x) x
curve(Lambda, 0, 40)
T_0 <- rpois(1, 40)
gen_z <- function() runif(1, 0.5, 1.5)
n <- 150
X <- cbind(
	sin(1:n), 
	sample(c(0, 1), n, TRUE), 
	sample(c(0, 1), n, TRUE), 
	sample(c(0, 1), n, TRUE), 
	sample(c(0, 1), n, TRUE))
beta <- rnorm(ncol(X))
```

## Generating Data

```{r gen2}
dev.off()
y <- rpois(n, T_0)
y <- as.numeric(ifelse(y < T_0, y, T_0))
t <- sapply(seq_along(y), function(i) {
	# 	browser()
	z <- gen_z() * exp(as.vector(X[i,] %*% beta))
	lambda_i <- function(t) z * lambda(t)
	retval <- gen_inhomo_poisson(lambda_i, y[i] - 1, lambda_i(0))
	if (is.null(retval)) return(vector("numeric", 0))
	return(retval)
	# 	return(as.numeric(ceiling(retval)))
})
obj <- new("recurrent-data", X, y, t, data.frame(), T_0)
```

## $\hat{\Lambda}$

```{r Lambda.hat2}
c.hat.gen <- recurrentR:::c.hat.gen(obj)
ci <- sapply(1:length(t), c.hat.gen)
# 	obj$Lambda.hat(T_0)

x.eval <- seq(0, obj@T_0, length=100)
y.eval <- obj$Lambda.hat(x.eval)
gamma <- obj$U.hat()
system.time({
	v <- asymptotic.var(obj, gamma = gamma)
	v.eval <- sapply(x.eval, function(x) v$Lambda.hat.var(x))
})
u.eval <- y.eval + 2*sqrt(v.eval)
l.eval <- y.eval - 2*sqrt(v.eval)
plot(x.eval, Lambda(x.eval), type="l", xlab="x", ylab="", 
	col = 3, lwd = 2, ylim=c(min(l.eval), max(u.eval)))
lines(x.eval, y.eval, lty=1, col = 1)
lines(x.eval, l.eval, lty=2)
lines(x.eval, u.eval, lty=2)
Lambda.hat <- obj$Lambda.hat
system.time({
	b.eval <- Lambda.hat(x.eval, bootstrap=TRUE)
})
u.eval <- y.eval + 2 * b.eval$error.measurement
l.eval <- y.eval - 2 * b.eval$error.measurement
lines(x.eval, u.eval, col=2, lty=2)
lines(x.eval, l.eval, col=2, lty=2)

m <- 100
real.sim <- matrix(0, length(x.eval), m)
U.sim <- matrix(0, length(beta) + 1, m)
# pb <- txtProgressBar(style=3, max=m)
for(i in 1:m) {
	y.sim <- rpois(n, T_0)
	y.sim <- as.numeric(ifelse(y.sim < T_0, y.sim, T_0))
	t.sim <- sapply(seq_along(y.sim), function(i) {
		# 	browser()
		z <- gen_z() * exp(as.vector(X[i,] %*% beta))
		lambda_i <- function(t) z * lambda(t)
		retval <- gen_inhomo_poisson(lambda_i, y.sim[i] - 1, lambda_i(0))
		if (is.null(retval)) return(vector("numeric", 0))
		return(retval)
		# 	return(as.numeric(ceiling(retval)))
	})
	obj.sim <- new("recurrent-data", X, y.sim, t.sim, data.frame(), T_0)
	real.sim[,i] <- obj.sim$Lambda.hat(x.eval)
	U.sim[,i] <- obj.sim$U.hat()
# 	setTxtProgressBar(pb, i)
}
# close(pb)

lines(x.eval, apply(real.sim, 1, function(a) quantile(a, 0.025)), lty=2, col=3, lwd=2)
lines(x.eval, apply(real.sim, 1, function(a) quantile(a, 0.975)), lty=2, col=3, lwd=2)

legend("bottomright", 
	c("Lambda.hat", "Lambda", "asymptotic pointwise C.I.", "bootstrap pointwise C.I.", "parametric bootstrap pointwise C.I."), 
	lty=c(1, 1, 2, 2, 2), col=c(1, 3, 1, 2, 3), lwd=c(1, 2, 1, 1, 2))
```

## $\hat{\gamma}$

- black: asymptotic C.I.
- red: bootstrap C.I.
- green: parametric bootstrap C.I. (quantile)

```{r gamma.hat2}
library(plotrix)
par(mfrow=c(1, length(gamma)))
asymptotic.gamma.sd <- sqrt(diag(v$gamma.var.hat))
invisible(capture.output(u.hat <- obj$U.hat(TRUE)))
param.bootstrap.U <- apply(U.sim, 1, function(a) quantile(a, c(0.025, 0.975)))
for(i in seq_along(gamma)) {
	plotCI(1:3, rep(gamma[i], 3), ui = c(gamma[i] + 2 * asymptotic.gamma.sd[i], gamma[i] + 2 * u.hat$error.measurement[i], param.bootstrap.U[2,i]), li=c(gamma[i] - 2 * asymptotic.gamma.sd[i], gamma[i] - 2 * u.hat$error.measurement[i], param.bootstrap.U[1,i]), 
		xaxt='n', xlab="", ylab = "", main=paste("gamma[", i, "]", sep=""), col=c(1,2,3), bty="n", xlim=c(0,3))
	if (i == 1) abline(h=log(Lambda(T_0)), col=3, lwd=2) else abline(h=beta[i-1], col=3, lwd=2)
}
```
