// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eval_N
SEXP eval_N(NumericVector s, NumericVector y, IntegerVector m);
RcppExport SEXP recurrentR_eval_N(SEXP sSEXP, SEXP ySEXP, SEXP mSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        NumericVector s = Rcpp::as<NumericVector >(sSEXP);
        NumericVector y = Rcpp::as<NumericVector >(ySEXP);
        IntegerVector m = Rcpp::as<IntegerVector >(mSEXP);
        SEXP __result = eval_N(s, y, m);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// step_integrate_kernel
SEXP step_integrate_kernel(Function g, NumericVector x, NumericVector p, double a, double b);
RcppExport SEXP recurrentR_step_integrate_kernel(SEXP gSEXP, SEXP xSEXP, SEXP pSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Function g = Rcpp::as<Function >(gSEXP);
        NumericVector x = Rcpp::as<NumericVector >(xSEXP);
        NumericVector p = Rcpp::as<NumericVector >(pSEXP);
        double a = Rcpp::as<double >(aSEXP);
        double b = Rcpp::as<double >(bSEXP);
        SEXP __result = step_integrate_kernel(g, x, p, a, b);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
