# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export StepFunction
NULL

step_integrate_kernel <- function(g, x, p, a, b) {
    .Call('recurrentR_step_integrate_kernel', PACKAGE = 'recurrentR', g, x, p, a, b)
}

